dataset:
  name: "mteb/banking77"
  text_column: "text"
  label_column: "label"

model:
  name: "Qwen/Qwen3.5-0.8B"
  num_labels: 77
  freeze_backbone: false # Set to true to freeze the backbone and train only the classification head

training:
  epochs: 3
  batch_size: 16
  seed: 42
  max_tokens: 100 #  10000000 # Uncomment to train for a specific number of tokens instead of epochs

optimizer:
  name: "LOZO" # Can be LOZO, LOZOM, or standard optimizers like AdamW
  kwargs:
    lr: 1.0e-5
    eps: 1.0e-3
    r: 4
    nu: 50
    # beta: 0.9 # Uncomment if using LOZOM

hub:
  push_to_hub: true
  repo_id: "Nbiescas/lozo-qwen-banking77" # IMPORTANT: Change to your actual HF username/repo!
