dataset:
  name: "mteb/banking77"
  text_column: "text"
  label_column: "label"

model:
  name: "Qwen/Qwen3.5-0.8B"
  freeze_backbone: false

training:
  epochs: 200
  batch_size: 16
  seed: 42
  #max_tokens: 100000

optimizer:
  name: "SGD"
  kwargs:
    lr: 1.0e-4
    momentum: 0.9

hub:
  push_to_hub: true
  repo_id: "mpilligua/sgd-generative-qwen-banking77"
