dataset:
  name: "mteb/banking77"
  text_column: "text"
  label_column: "label"

model:
  name: "Qwen/Qwen3.5-0.8B"
  freeze_backbone: false # Backbone must be fully trainable for true zeroth-order capability validation

training:
  epochs: 400
  batch_size: 16 # Maximizing A100 VRAM utilization for high-throughput zeroth-order training
  seed: 42
  eval_steps: null
  eval_epochs: 10
  #max_tokens: 100000 # Uncomment to train for specific token counts instead of epochs
  lr_scheduler:
    type: "cosine"
    warmup_ratio: 0.05
    start_lr: 1.0e-7

optimizer:
  name: "LOZO" # Can be LOZO or LOZOM
  kwargs:
    lr: 1.0e-6
    eps: 1.0e-3
    r: 8
    nu: 100

hub:
  push_to_hub: true
  repo_id: "Nbiescas/lozo-generative-qwen-banking77_cosine_v2"
