dataset:
  template: "mezo"
  task: "copa"
  num_train: 1000
  num_dev: 500
  num_eval: 1000

model:
  name: "Qwen/Qwen2.5-0.5B"
  dtype: "float16"

training:
  seed: 87
  batch_size: 16
  max_steps: 20000
  eval_steps: 500
  lr_scheduler:
    type: "constant"

optimizer:
  name: "LOZO"
  kwargs:
    lr: 1e-7
    eps: 1e-3
    weight_decay: 0.0
    r: 1
    nu: 100

hub:
  push_to_hub: true
  repo_id: "Nbiescas/zo-lozo-copa-qwen"
