dataset:
  template: "mezo"
  task: "sst2" # overridden by --task
  num_train: 1000
  num_dev: 500
  num_eval: 1000

model:
  name: "facebook/opt-1.3b"
  dtype: "float16"

training:
  max_steps: 20000
  batch_size: 16
  seed: 42
  eval_steps: 500

optimizer:
  name: "PseuZO"
  kwargs:
    first_order_name: "SGD"
    lr: 1.0e-7
    zo_eps: 1.0e-3
    momentum_fb: 0.9
    weight_decay: 0.0
