dataset:
  template: "mezo"
  task: "copa"
  num_train: 1000
  num_dev: 500
  num_eval: 1000

model:
  name: "Qwen/Qwen2.5-0.5B"
  dtype: "float16"

training:
  seed: 42
  batch_size: 16
  max_steps: 20000
  eval_steps: 500
  lr_scheduler:
    type: "constant"

optimizer:
  name: "PseuZO"
  kwargs:
    lr: 1e-7
    zo_eps: 1e-3
    weight_decay: 0.0
    momentum_fb: 0.0

hub:
  push_to_hub: true
  repo_id: "Nbiescas/zo-pseuzo-copa-qwen"
