dataset:
  name: "csv"
  delimiter: "\t"
  data_files:
    train: "../LOZO/data/k-shot-1k-test/RTE/16-42/train.tsv"
    validation: "../LOZO/data/k-shot-1k-test/RTE/16-42/dev.tsv"
    test: "../LOZO/data/k-shot-1k-test/RTE/16-42/test.tsv"
  text_column: "sentence1"
  text_column2: "sentence2"
  label_column: "label"

model:
  name: "roberta-large"
  freeze_backbone: false

training:
  epochs: 10000
  batch_size: 64
  seed: 42
  eval_epochs: 1000

optimizer:
  name: "LOZO"
  kwargs:
    lr: 1.0e-6
    eps: 1.0e-3
    r: 4
    nu: 100

hub:
  push_to_hub: false
